version: "3.9"

services:
  api:
    container_name: api-emailer
    build: .
    env_file: .env
    environment:
      PORT: 80
    ports:
      - "8000:80"
    command: npm run queue:mailer
      
  redis:
    container_name: redis-emailer
    image: "redis:alpine"
    ports: 
      - "6379:6379"