version: "3.9"

services:
  api:
    container_name: api-emailer
    build: .
    env_file: .env.production
    ports:
      - "8000:80"
    volumes: 
      - .:/usr/src/app
      
  redis:
    container_name: redis-emailer
    image: "redis:alpine"
    ports: 
      - "6379:6379"